[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.27.2"
eframe = "0.27.2"

opencv = {version = "0.92.0" }
rfd = "0.14.1"
tokio = { features = ["full"] }
